name: Validate renovate.json

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.0
          cache: npm

      - name: Install Renovate CLI
        run: npm install -g renovate

      - name: Validate renovate.json
        run: renovate-config-validator
