name: Validate renovate.json

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  renovate-config-validator:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: npm

      - name: Install Renovate CLI
        run: npm install -g renovate

      - name: Validate renovate.json
        run: renovate-config-validator
